#!/bin/sh
rm *~
rm gap/*~
rm examples/*~
rm draft/*~
cd doc
make_doc
cd ../draft
latex rcwa
latex rcwa
rm *.aux *.log
cd ..
to_dos
cd ..
rm rcwa.zip
zip -r rcwa.zip rcwa/*
cd rcwa
to_unix
cd ..
rm -f README.rcwa rcwa.zoo
cp rcwa/readme.txt README.rcwa
find rcwa -type f | egrep -v 'CVS|zoo|bin|wrap_up|to_dos|to_unix|make_doc|[.]cvs|[.]aux|[.]toc|[.][ib]lg|[.]log|[.]ind|[.]idx|[.]lab|[.]swp|[.]bak|~|[.]#' | zoo ahI rcwa.zoo
cd rcwa

