name: RCWA
version: 4.6.4
date: 2019-03-24
description: |
    Residue-Class-Wise Affine Groups

authors:
    - name: Stefan Kohl
      url: https://stefan-kohl.github.io/

maintainers:
    - name: Stefan Kohl
      url: https://stefan-kohl.github.io/

GAP: ">=4.9.1"

needed-pkgs:
    - name: "ResClasses"
      version: ">=4.7.2"
      url: "https://gap-packages.github.io/resclasses/"
    - name: "GRAPE"
      version: ">=4.7"
      url: "https://gap-packages.github.io/grape"
    - name: "Polycyclic"
      version: ">=2.11"
      url: "https://gap-packages.github.io/polycyclic/"
    - name: "FR"
      version: ">=2.2.1"
      url: "https://gap-packages.github.io/fr"
    - name: "GAPDoc"
      version: ">=1.5.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "Utils"
      version: ">=0.40"
      url: "https://gap-packages.github.io/utils"

www: https://gap-packages.github.io/rcwa/
readme: README.md
packageinfo: https://gap-packages.github.io/rcwa/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/rcwa/releases/download/v4.6.4/rcwa-4.6.4.tar.gz

abstract: |
    This package provides implementations of algorithms and methods for computation in certain infinite permutation groups. For an abstract, see <a href = "https://gap-packages.github.io/rcwa/">here</a>.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
