name: RCWA
version: "4.8.0"
license: "GPL-2.0-or-later"
date: 2025-09-22
description: |
    Residue-Class-Wise Affine Groups

authors:
    - name: Stefan Kohl
      url: https://stefan-kohl.github.io/

maintainers:
    - name: Stefan Kohl
      url: https://stefan-kohl.github.io/

GAP: ">=4.12.0"

needed-pkgs:
    - name: "ResClasses"
      version: ">=4.7.2"
      url: "https://gap-packages.github.io/resclasses/"
    - name: "GRAPE"
      version: ">=4.7"
      url: "https://gap-packages.github.io/grape"
    - name: "Polycyclic"
      version: ">=2.11"
      url: "https://gap-packages.github.io/polycyclic/"
    - name: "FR"
      version: ">=2.2.1"
      url: "https://gap-packages.github.io/fr"
    - name: "GAPDoc"
      version: ">=1.5.1"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "Utils"
      version: ">=0.40"
      url: "https://gap-packages.github.io/utils"

www: https://gap-packages.github.io/rcwa/
readme: README.md
packageinfo: https://gap-packages.github.io/rcwa/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/rcwa/releases/download/v4.8.0/rcwa-4.8.0.tar.gz

abstract: |
    This package provides implementations of algorithms and methods for computation in certain infinite permutation groups.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    infinite permutation groups, permutation groups over rings, combinatorial group theory, residue-class-wise affine groups, residue-class-wise affine mappings, Collatz conjecture, 3n+1 conjecture.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Koh25</span>]   <b class='BibAuthor'>Kohl, S.</b>,
     <i class='BibTitle'>RCWA, Residue-Class-Wise Affine Groups,
             Version 4.8.0</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/rcwa/">https://gap-packages.github.io/rcwa/</a></span>.
    </p>
    

bibtex: |
    @misc{ RCWA,
      author =           {Kohl, S.},
      title =            {{RCWA},
                          {Residue\texttt{\symbol{45}}Class\texttt{\symbol{45}}Wise
                          Affine Groups}, {V}ersion 4.8.0},
      month =            {Sep},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href           {https://gap-packages.github.io/rcwa/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{rcwa/}}},
      keywords =         {infinite  permutation  groups; permutation groups over
                          rings;        combinatorial        group       theory;
                          residue\texttt{\symbol{45}}class\texttt{\symbol{45}}wise
                          affine                                         groups;
                          residue\texttt{\symbol{45}}class\texttt{\symbol{45}}wise
                          affine mappings; Collatz conjecture; 3n+1 conjecture},
      printedkey =       {Koh25}
    }

